version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: epl_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: .
    environment:
      DB_NAME: epl_db
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: db
      REDIS_URL: redis://redis:6379
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data:
